import { setLocalStorage, getLocalStorage, removeLocalStorage } from '../utils/localStorage';
import FormCadastro from '@/components/form-cadastro'
import { useAxios } from '@/hooks/useAxios'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router';
import { useUserStore } from '@/features/zustand/userStore';

export default function Home() {
  const [showModalCadastro, setShowModalCadastro] = useState(false)
  const router = useRouter();
  const { api } = useAxios();
  const { setUser } = useUserStore();

  useEffect(() => {
    const user = getLocalStorage('user-restaurantes');
    if (user) {
      router.push('/home');
    }
  }, [router])

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()

    const usuario = {
      email: event.currentTarget.email.value,
      senha: event.currentTarget.password.value,
    }

    api.post('/login', usuario)
      .then((response) => {
        console.log(response);
        setUser(response.data);
        localStorage.setItem('user-restaurantes', JSON.stringify(response.data));
        router.push('/home');
      })
      .catch((error) => {
        console.log(error);
      })
  }


  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Next.js + Tailwind CSS</title>
      </Head>
      <main className="flex min-h-screen flex-col items-center p-24">
        <form onSubmit={handleSubmit} className="w-full flex-col flex justify-center items-center bg-purple-500 shadow-lg p-5 rounded-md max-w-sm">
          <div className="md:flex md:items-center mb-6">
            <div className="md:w-1/3">
              <label className="block text-white font-bold md:text-right mb-1 md:mb-0 pr-4" htmlFor="username">
                Email
              </label>
            </div>
            <div className="md:w-2/3">
              <input
                autoComplete='email'
                className="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
                id="email"
                type="email"
                placeholder="Seu email"
              />
            </div>
          </div>
          <div className="md:flex md:items-center mb-6">
            <div className="md:w-1/3">
              <label className="block text-white  font-bold md:text-right mb-1 md:mb-0 pr-4" htmlFor="password">
                Senha
              </label>
            </div>
            <div className="md:w-2/3">
              <input
                autoComplete='current-password'
                className="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
                id="password"
                type="password"
                placeholder="Sua senha"
              />
            </div>
          </div>
          <div className="md:flex md:items-center">
            <div className="md:w-3/3">
              <button
                className="shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded"
                type="submit"
              >
                Entrar
              </button>
            </div>
          </div>
        <p className="mt-4 text-white">
          Não tem uma conta?{' '}
          <span onClick={() => setShowModalCadastro(true)}>
            Cadastre-se
          </span>
        </p>
        </form>
      </main>
      <FormCadastro showModal={showModalCadastro} onRequestClose={() => setShowModalCadastro(!showModalCadastro)} />
    </>
  )
}
